version: '3'

services:
  db:
    image: neo4j:3.5.3
    ports:
      - "7474:7474" # http
      - "7687:7687" # bolt
    volumes:
      - ./data:/var/lib/neo4j/import/data

  app:
    build: .
    volumes:
      - ./app:/app
      - ./data:/data



